"""Recipes visuelles : stockage, compilation en SQL dbt, aperçu par étape.

Le modèle est celui d'un ETL visuel classique — dataset → recipe → dataset —
posé sur dbt : une recipe produit exactement un modèle dbt, et chaque étape du
script devient un CTE nommé et commenté. Le `.sql` reste lisible et reste la
vérité ; la recipe n'est que la décomposition qui a servi à l'écrire.

Ce fichier ne contient que la façade. Le travail est réparti en modules qui ne
connaissent que ceux qui les précèdent :

    errors      le refus d'une recipe
    vocabulary  les valeurs fermées que dbt impose
    dialect     l'entrepôt pour lequel on écrit, et ses trois noms
    sql         citer un identifiant, écrire un littéral
    writers     ce qui ne s'écrit pas pareil d'une famille à l'autre
    names       ce qu'on accepte d'écrire : noms et expressions
    columns     l'état des colonnes au fil d'un script, le SQL d'une étape
    spec        la forme d'un script visuel
    refs        les ref() et source() : les écrire, les faire suivre
    processors  une fonction par geste de la recipe Préparer
    describe    la phrase lue sur la carte d'une étape
    config      le {{ config() }} et la machinerie incrémentale
    compilers   recipe → SQL dbt, un compilateur par type
    storage     les scripts visuels sur le disque

Tout ce que le module rendait reste rendu ici : `from pliq import recipes as
rcp` puis `rcp.compile_recipe(...)` s'écrit comme avant.
"""

from __future__ import annotations

from .vocabulary import (
    BATCH_SIZES,
    FILTER_OPERATORS,
    INCREMENTAL_STRATEGIES,
    LOOKBACK_UNITS,
    MATERIALIZATIONS,
    ON_SCHEMA_CHANGE,
    PIVOT_AGGREGATIONS,
    NO_VALUE_OPERATORS,
    RECIPE_TYPES,
    SINGLE_VALUE_OPERATORS,
    STRATEGIES_NEEDING_KEY,
)
from .errors import (
    RecipeError,
)
from .dialect import (
    Dialect,
    GENERIC,
    GENERIC_DIALECT,
    _FAMILIES,
    current_dialect,
    using_dialect,
    family,
    set_dialect,
)
from .sql import (
    NAME_RE,
    RESERVED,
    SIMPLE_IDENT,
    as_int,
    lit,
    q,
    typed_lit,
)
from .writers import (
    APPROX_MEDIAN,
    DATE_PARTS,
    LIKE_ESCAPE,
    as_text,
    date_minus,
    date_part,
    empty_sql,
    filled_sql,
    like_literal,
    like_predicate,
    median,
    median_is_approximate,
    parse_timestamp,
    safe_cast,
    split_part,
    substring,
    text_type,
    time_format,
    type_family,
    types_offered,
)
from .names import (
    check_expr,
    check_predicate,
    dbt_name,
    jinja_str,
    validate_name,
)
from .columns import (
    ColumnState,
    StepSql,
    _check_unique_columns,
)
from .spec import (
    check_max_inputs,
    check_spec_shape,
    free_cte,
    input_alias,
    input_aliases,
    input_label,
    model_path,
)
from .refs import (
    NON_COLUMN_KEYS,
    column_texts,
    mentions_column,
    ref_re,
    ref_sql,
    ref_version,
    rename_ref_in_spec,
    rename_ref_in_sql,
    sql_mentions_column,
)
from .processors import (
    OPERATORS,
    PROCESSORS,
    WINDOW_COUNTS,
    WINDOW_FUNCTIONS,
    WINDOW_NEEDS_COLUMN,
    WINDOW_NEEDS_ORDER,
    _predicate,
    p_change_type,
    p_concat,
    p_date_parts,
    p_dedup_key,
    p_distinct,
    p_fill_empty,
    p_filter_formula,
    p_filter_value,
    p_find_replace,
    p_formula,
    p_if,
    p_keep_delete,
    p_parse_date,
    p_pivot,
    p_remove_empty,
    p_rename,
    p_round,
    p_sort,
    p_split,
    p_text,
    p_unpivot,
    p_window,
    pivot_alias,
    processor,
)
from .describe import (
    describe_step,
)
from .config import (
    check_microbatch_output,
    check_strategy_supported,
    config_block,
    default_strategy,
    strategies_available,
    strategy_of,
    incremental_column,
    incremental_filter,
    incremental_group_filter,
    incremental_predicate,
    incremental_where,
    lookback_window,
    microbatch,
    microbatch_entries,
)
from .compilers import (
    AGGREGATIONS,
    COMPILERS,
    FINAL_SELECT,
    JOIN_TYPES,
    _aggregate,
    compile_group,
    compile_join,
    compile_prepare,
    compile_recipe,
    compile_sql,
    compile_stack,
    final_select,
    join_config,
    join_from_lines,
    output_columns,
    rename_banner,
    renamed_columns,
    source_cte,
)
from .storage import (
    DOC_FIELDS,
    RECIPE_DIR,
    delete_recipe,
    infer_type,
    library,
    list_recipes,
    load_recipe,
    readonly_reason,
    recipes_and_errors,
    recipe_file,
    save_recipe,
    stored_spec,
)

__all__ = [
    "AGGREGATIONS",
    "APPROX_MEDIAN",
    "BATCH_SIZES",
    "COMPILERS",
    "DATE_PARTS",
    "DOC_FIELDS",
    "FILTER_OPERATORS",
    "FINAL_SELECT",
    "GENERIC",
    "GENERIC_DIALECT",
    "INCREMENTAL_STRATEGIES",
    "JOIN_TYPES",
    "LIKE_ESCAPE",
    "LOOKBACK_UNITS",
    "MATERIALIZATIONS",
    "NAME_RE",
    "NON_COLUMN_KEYS",
    "NO_VALUE_OPERATORS",
    "ON_SCHEMA_CHANGE",
    "OPERATORS",
    "PIVOT_AGGREGATIONS",
    "PROCESSORS",
    "RECIPE_DIR",
    "RECIPE_TYPES",
    "RESERVED",
    "SIMPLE_IDENT",
    "SINGLE_VALUE_OPERATORS",
    "STRATEGIES_NEEDING_KEY",
    "WINDOW_COUNTS",
    "WINDOW_FUNCTIONS",
    "WINDOW_NEEDS_COLUMN",
    "WINDOW_NEEDS_ORDER",
    "_FAMILIES",
    "ColumnState",
    "Dialect",
    "RecipeError",
    "StepSql",
    "_aggregate",
    "_check_unique_columns",
    "_predicate",
    "as_int",
    "as_text",
    "check_expr",
    "check_max_inputs",
    "check_microbatch_output",
    "check_predicate",
    "check_spec_shape",
    "check_strategy_supported",
    "column_texts",
    "compile_group",
    "compile_join",
    "compile_prepare",
    "compile_recipe",
    "compile_sql",
    "compile_stack",
    "config_block",
    "current_dialect",
    "date_minus",
    "date_part",
    "dbt_name",
    "default_strategy",
    "delete_recipe",
    "describe_step",
    "empty_sql",
    "family",
    "filled_sql",
    "final_select",
    "free_cte",
    "incremental_column",
    "incremental_filter",
    "incremental_group_filter",
    "incremental_predicate",
    "incremental_where",
    "infer_type",
    "input_alias",
    "input_aliases",
    "input_label",
    "jinja_str",
    "join_config",
    "join_from_lines",
    "library",
    "like_literal",
    "like_predicate",
    "list_recipes",
    "lit",
    "load_recipe",
    "lookback_window",
    "median",
    "median_is_approximate",
    "mentions_column",
    "microbatch",
    "microbatch_entries",
    "model_path",
    "output_columns",
    "p_change_type",
    "p_concat",
    "p_date_parts",
    "p_dedup_key",
    "p_distinct",
    "p_fill_empty",
    "p_filter_formula",
    "p_filter_value",
    "p_find_replace",
    "p_formula",
    "p_if",
    "p_keep_delete",
    "p_parse_date",
    "p_pivot",
    "p_remove_empty",
    "p_rename",
    "p_round",
    "p_sort",
    "p_split",
    "p_text",
    "p_unpivot",
    "p_window",
    "parse_timestamp",
    "pivot_alias",
    "processor",
    "q",
    "readonly_reason",
    "recipe_file",
    "recipes_and_errors",
    "ref_re",
    "ref_sql",
    "ref_version",
    "rename_banner",
    "rename_ref_in_spec",
    "rename_ref_in_sql",
    "renamed_columns",
    "safe_cast",
    "save_recipe",
    "set_dialect",
    "source_cte",
    "split_part",
    "sql_mentions_column",
    "stored_spec",
    "strategies_available",
    "strategy_of",
    "substring",
    "text_type",
    "time_format",
    "type_family",
    "typed_lit",
    "types_offered",
    "using_dialect",
    "validate_name",
]
